name: mc-FunGun
version: '${project.version}'
main: hu.kxtsoo.fungun.FunGun
api-version: '1.16'
folia-supported: true
authors: [ "kxtsoo", "Zsomi5", "Leonidas"]
softdepend:
  - PlaceholderAPI

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214