name: mc-FunGun
version: '2.0.2'
main: hu.kxtsoo.fungun.FunGun
api-version: '1.16'
folia-supported: true
authors: [ kxtsoo ]

libraries:
  - dev.dejvokep:boosted-yaml:1.3
  - com.zaxxer:HikariCP:5.1.0
  - com.h2database:h2:2.1.214

commands:
  mcfungun:
    alias: ["mc-fungun", "fungun"]
    description: 'List the command arguments'
    subcommands:
      reload:
        description: 'Reload the plugin files.'
        usage: '/mcfungun reload'
      give:
        description: 'Give a FunGun item to player'
        usage: '/mcfungun give <player> [slot]'